//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinMart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.AddressUsers = new HashSet<AddressUser>();
            this.CartDetails = new HashSet<CartDetail>();
            this.Purchases = new HashSet<Purchase>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string displayName { get; set; }
        public int position { get; set; }
        public string email { get; set; }
        public int idAccountDetail { get; set; }
    
        public virtual AccountDetail AccountDetail { get; set; }
        public virtual AccountPosition AccountPosition { get; set; }
        public virtual ICollection<AddressUser> AddressUsers { get; set; }
        public virtual ICollection<CartDetail> CartDetails { get; set; }
        public virtual ICollection<Purchase> Purchases { get; set; }
    }
}
