//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinMart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BigCategory
    {
        public BigCategory()
        {
            this.Categories = new HashSet<Category>();
        }
    
        public int id { get; set; }
        public string displayName { get; set; }
        public string mediaURL { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
    }
}
