//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinMart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public ProductDetail()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int id { get; set; }
        public string ingredients { get; set; }
        public string preserve { get; set; }
        public string origin { get; set; }
        public string manuals { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
