//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinMart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public Purchase()
        {
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
        }
    
        public int id { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<System.DateTime> createAt { get; set; }
        public Nullable<int> idDeliveryAddress { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual DeliveryAddress DeliveryAddress { get; set; }
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
    }
}
